version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
    open-pull-requests-limit: 3
    groups:
      production:
        patterns: ["*"]
        exclude-patterns: ["@types/*", "eslint*"]
      dev-dependencies:
        dependency-type: "development"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
