version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/tec-api-gateway"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 2

  - package-ecosystem: "npm"
    directory: "/tec-auth-service"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 2

  - package-ecosystem: "npm"
    directory: "/tec-payment-service"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 2

  - package-ecosystem: "npm"
    directory: "/tec-wallet-service"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 2

  - package-ecosystem: "npm"
    directory: "/tec-notification-service"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 2

  - package-ecosystem: "npm"
    directory: "/tec-kyc-service"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 2

  - package-ecosystem: "npm"
    directory: "/tec-commerce-service"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 2

  - package-ecosystem: "npm"
    directory: "/tec-asset-service"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 2

  - package-ecosystem: "npm"
    directory: "/shared"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 2

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 2
